server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    # 정적 파일 서빙
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 업로드 파일 캐시 비활성화
    location /uploads/ {
        expires -1;
        add_header Cache-Control "no-store";
    }

    # 불필요한 파일 접근 차단
    location ~ \.(py|env|bat|sh|md|gitignore)$ {
        deny all;
        return 404;
    }
}
